---
- hosts:
  - localhost
  vars:
    package_state: present

  roles:
    - {role: general_utils, tags: utils}
    - {role: dot_file_stuff, tags: dot}
    - {role: iterm, tags: terminals}
    - {role: vim, tags: vim}
    - {role: editors, tags: editors}
    - {role: virtualbox, tags: virtualbox}
    - {role: docker, tags: docker}
    - {role: vagrant, tags: vagrant}
    - {role: browsers, tags: browsers}
    - {role: java, tags: java}
    - {role: kubernetes, tags: kubernetes}
    - {role: javascript, tags: javascript}
