---
- name: Add Docker Repository
  yum_repository:
    name: docker-ce
    description: Docker CE
    baseurl:  https://download.docker.com/linux/fedora/docker-ce.repo
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: yes
 
- name: Install Docker kvm2 driver
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2"
    dest: /tmp
  become: yes

- name: Copy Docker kvm2 to usr/local/bin
  copy:
    src: /tmp/docker-machine-driver-kvm2
    dest: /usr/local/bin/docker-machine-driver-kvm2
    mode: "+x"

- name: Install Docker
  dnf:
    name:
      - docker
    state: "{{ package_state }}"

- name: Enable and Start Docker service
  systemd:
    name: docker.service
    enabled: yes
    state: started
    masked: no
